class PosTicket




end


["_embedded", "_links", "auto_send", "closed_at", "guest_count", "id", "name", "open", "opened_at", "ticket_number", "totals", "void"]

{"_embedded"=>
  {"discounts"=>[],
   "employee"=>
    {"_links"=>
      {"self"=>
        {"etag"=>"934d3a9ae389e3279fd443cdb05f80cc",
         "href"=>
          "https://api.omnivore.io/0.1/locations/qxi55kTj/employees/BdTaKT4X/",
         "profile"=>"https://panel.omnivore.io/docs/api#employee_retrieve"}},
     "check_name"=>"Bob",
     "first_name"=>"Bob",
     "id"=>"BdTaKT4X",
     "last_name"=>"Belcher",
     "login"=>"100"},
   "items"=>
    [{"_embedded"=>
       {"discounts"=>[],
        "menu_item"=>
         {"_links"=>
           {"modifier_groups"=>
             {"href"=>
               "https://api.omnivore.io/0.1/locations/qxi55kTj/menu/items/rMTAbTjr/modifier_groups/",
              "profile"=>
               "https://panel.omnivore.io/docs/api#modifier-group_list"},
            "self"=>
             {"etag"=>"21152ae3c6141b600f161912b363e0f0",
              "href"=>
               "https://api.omnivore.io/0.1/locations/qxi55kTj/menu/items/rMTAbTjr/",
              "profile"=>
               "https://panel.omnivore.io/docs/api#menu-item_retrieve"}},
          "id"=>"rMTAbTjr",
          "in_stock"=>false,
          "modifier_groups_count"=>2,
          "name"=>"New Bacon-ings",
          "open"=>false,
          "pos_id"=>"rMTAbTjr",
          "price"=>689,
          "price_levels"=>[{"id"=>"7oTd8T9A", "price"=>689}]},
        "modifiers"=>[]},
      "_links"=>
       {"discounts"=>
         {"href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/acrBzkTB/discounts/",
          "profile"=>"https://panel.omnivore.io/docs/api#discount_list"},
        "menu_item"=>
         {"href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/menu/items/rMTAbTjr/",
          "profile"=>"https://panel.omnivore.io/docs/api#menu-item_retrieve"},
        "modifiers"=>
         {"href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/acrBzkTB/modifiers/",
          "profile"=>"https://panel.omnivore.io/docs/api#modifier_list"},
        "self"=>
         {"etag"=>"d36064ca4156f4c37d440215e6f00559",
          "href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/acrBzkTB/",
          "profile"=>"https://panel.omnivore.io/docs/api#item_retrieve"}},
      "comment"=>"Burned",
      "id"=>"acrBzkTB",
      "name"=>"New Bacon-ings",
      "price_level"=>"7oTd8T9A",
      "price_per_unit"=>689,
      "quantity"=>2,
      "sent"=>true},
     {"_embedded"=>
       {"discounts"=>[],
        "menu_item"=>
         {"_links"=>
           {"modifier_groups"=>
             {"href"=>
               "https://api.omnivore.io/0.1/locations/qxi55kTj/menu/items/rMTAbTjr/modifier_groups/",
              "profile"=>
               "https://panel.omnivore.io/docs/api#modifier-group_list"},
            "self"=>
             {"etag"=>"21152ae3c6141b600f161912b363e0f0",
              "href"=>
               "https://api.omnivore.io/0.1/locations/qxi55kTj/menu/items/rMTAbTjr/",
              "profile"=>
               "https://panel.omnivore.io/docs/api#menu-item_retrieve"}},
          "id"=>"rMTAbTjr",
          "in_stock"=>false,
          "modifier_groups_count"=>2,
          "name"=>"New Bacon-ings",
          "open"=>false,
          "pos_id"=>"rMTAbTjr",
          "price"=>689,
          "price_levels"=>[{"id"=>"7oTd8T9A", "price"=>689}]},
        "modifiers"=>[]},
      "_links"=>
       {"discounts"=>
         {"href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/4ix5y6cj/discounts/",
          "profile"=>"https://panel.omnivore.io/docs/api#discount_list"},
        "menu_item"=>
         {"href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/menu/items/rMTAbTjr/",
          "profile"=>"https://panel.omnivore.io/docs/api#menu-item_retrieve"},
        "modifiers"=>
         {"href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/4ix5y6cj/modifiers/",
          "profile"=>"https://panel.omnivore.io/docs/api#modifier_list"},
        "self"=>
         {"etag"=>"0bac81052d0d480f056abd98f83e055f",
          "href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/4ix5y6cj/",
          "profile"=>"https://panel.omnivore.io/docs/api#item_retrieve"}},
      "comment"=>"",
      "id"=>"4ix5y6cj",
      "name"=>"New Bacon-ings",
      "price_level"=>"7oTd8T9A",
      "price_per_unit"=>689,
      "quantity"=>1,
      "sent"=>true}],
   "order_type"=>
    {"_links"=>
      {"self"=>
        {"etag"=>"f734af98716581abbfd84b0fc068ade7",
         "href"=>
          "https://api.omnivore.io/0.1/locations/qxi55kTj/order_types/KxiAaip5/",
         "profile"=>"https://panel.omnivore.io/docs/api#order-type_retrieve"}},
     "available"=>true,
     "id"=>"KxiAaip5",
     "name"=>"Eat In"},
   "payments"=>
    [{"_embedded"=>{},
      "_links"=>
       {"self"=>
         {"etag"=>"78bb1ceaeb40a6be89bc2caa58e9fad3",
          "href"=>
           "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/payments/qpcxjdiz/",
          "profile"=>"https://panel.omnivore.io/docs/api#payment_retrieve"}},
      "amount"=>300,
      "change"=>nil,
      "id"=>"qpcxjdiz",
      "last4"=>nil,
      "tip"=>0,
      "type"=>"other"}],
   "revenue_center"=>
    {"_links"=>
      {"self"=>
        {"etag"=>"1f193eaa99f131789890ea0001e7b07d",
         "href"=>
          "https://api.omnivore.io/0.1/locations/qxi55kTj/revenue_centers/LdiqGibo/",
         "profile"=>
          "https://panel.omnivore.io/docs/api#revenue-center_retrieve"}},
     "default"=>true,
     "id"=>"LdiqGibo",
     "name"=>"Dining"},
   "table"=>
    {"_links"=>
      {"self"=>
        {"etag"=>"0d5c8e60d8f7c998b71c26ff4dc9077b",
         "href"=>
          "https://api.omnivore.io/0.1/locations/qxi55kTj/tables/jLiyniEb/",
         "profile"=>"https://panel.omnivore.io/docs/api#table_retrieve"}},
     "available"=>true,
     "id"=>"jLiyniEb",
     "name"=>"1",
     "number"=>1,
     "seats"=>4},
   "voided_items"=>[]},
 "_links"=>
  {"discounts"=>
    {"href"=>
      "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/discounts/",
     "profile"=>"https://panel.omnivore.io/docs/api#discount_list"},
   "items"=>
    {"href"=>
      "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/items/",
     "profile"=>"https://panel.omnivore.io/docs/api#item_list"},
   "payments"=>
    {"href"=>
      "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/payments/",
     "profile"=>"https://panel.omnivore.io/docs/api#payment_list"},
   "self"=>
    {"etag"=>"b2bfc50073f939a2f237625d5152f183",
     "href"=>
      "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/",
     "profile"=>"https://panel.omnivore.io/docs/api#ticket_retrieve"},
   "table"=>
    {"href"=>"https://api.omnivore.io/0.1/locations/qxi55kTj/tables/jLiyniEb/",
     "profile"=>"https://panel.omnivore.io/docs/api#table_retrieve"},
   "voided_items"=>
    {"href"=>
      "https://api.omnivore.io/0.1/locations/qxi55kTj/tickets/g9izXxTd/voided_items/",
     "profile"=>"https://panel.omnivore.io/docs/api#voided-item_list"}},
 "auto_send"=>true,
 "closed_at"=>nil,
 "guest_count"=>1,
 "id"=>"g9izXxTd",
 "name"=>"ItsOnMe ticket",
 "open"=>true,
 "opened_at"=>1423789472,
 "ticket_number"=>697,
 "totals"=>
  {"due"=>1922,
   "other_charges"=>0,
   "service_charges"=>0,
   "sub_total"=>2067,
   "tax"=>155,
   "total"=>2222},
 "void"=>false}