#Define application variables here. The initializer file, app_config.rb will store this hash into APP_CONFIG.
#To call facebook, you can write APP_CONFIG[:facebook][:key]
#Note that we will construct the client-facing URL they need to click in order to log in with Facebook in the initializer file.
