development:
  adapter: postgresql
  encoding: unicode
  database: drinkboard_dev
  host: localhost
  pool: 5
  username: drinkboard
  password: drinkdrink

test:
  adapter: postgresql
  encoding: unicode
  database: drinkboard_test
  host: localhost
  pool: 5
  username: drinkboard
  password: drinkdrink

admt_development:
  adapter: postgresql
  encoding: unicode
  database: admintools_dev
  host: localhost
  pool: 5
  username: drinkboard
  password: drinkdrink

admt_test:
  adapter: postgresql
  encoding: unicode
  database: admintools_test
  host: localhost
  pool: 5
  username: jongutwillig
  password: drinkdrink

mt_development:
  adapter: postgresql
  encoding: unicode
  database: merchanttools_dev
  host: localhost
  pool: 5
  username: drinkboard
  password: drinkdrink

mt_test:
  adapter: postgresql
  encoding: unicode
  database: merchanttools_test
  host: localhost
  pool: 5
  username: jongutwillig
  password: drinkdrink
