defaults: &defaults
  adapter: postgresql
  username: admintools
  password: admintools
  host: 127.0.0.1

development:
  <<: *defaults
  database: drinkboard_development

mt_development:
  <<: *defaults
  database: mt_development

admt_development:
  <<: *defaults
  database: admintools_development

test:
  <<: *defaults
  database: drinkboard_test

mt_test:
  <<: *defaults
  database: mt_test

admt_test:
  <<: *defaults
  database: admintools_test
