class CreatePurchaseVerifications < ActiveRecord::Migration
  def change
    create_table :purchase_verifications do |t|
      t.string    :hex_id
      t.integer   :check_count, default: 0  # Reduces cost of averages reports
      t.string    :session_id               # Generated by the client.  Likely a UUID
      t.datetime  :expires_at               # Extended as we request each additional check
      t.datetime  :verified_at              # When the user passes all verification checks
      t.datetime  :failed_at                # Reduces cost of reports and subsequent purchase attempts
      t.integer   :user_id                  # For tracking
      t.integer   :merchant_id              # For reporting
      t.integer   :gift_id                  # present only if the verifications and subsequent purchase succeed.
      t.string    :cart                     # Actual cart the user is attempting to purchase.  Stored for fraud analysis
      t.string    :value                    # Gift value (in cents)
      t.string    :ccy, limit: 6, default: "USD"
      t.timestamps
    end

    add_index :purchase_verifications, :hex_id
  end
end
